# Generated by Django 3.1 on 2020-10-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images'),
        ),
    ]
